CREATE DATABASE IF NOT EXISTS calculatordb;
USE calculatordb;

CREATE TABLE IF NOT EXISTS history (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  expression VARCHAR(255) NOT NULL,
  result     VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);